name: CI

on:
  push:
    branches:
      - main
    paths:
      - "./tauri-app/**"
      - ".github/workflows/integration-frontend.yml"
  pull_request:
    branches:
      - main
    paths:
      - "./tauri-app/**"
      - ".github/workflows/integration-frontend.yml"

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tauri-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yarn
        run: npm install -g yarn

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: "tauri-app/yarn.lock"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Frontend Unit Tests
        run: yarn test:front

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: yarn e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
