name: CI for Backend
on:
  push:
    branches:
      - main
    paths:
      - "./tauri-app/src-tauri/**"
      - ".github/workflows/integration-backend.yml"
  pull_request:
    branches:
      - main
    paths:
      - "./tauri-app/src-tauri/**"
      - ".github/workflows/integration-backend.yml"

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tauri-app/src-tauri
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Lint Rust Code
        run: cargo clippy -- -D warnings

      - name: Run Backend Unit Tests
        run: cargo test --verbose
